easy_admin:
  design:
    menu:
      - {label: "Entity"}
      - label: "Centre"
        children: 
          - {entity: Centre, label: "Liste Centres", icon: "th-list"}
          - {entity: Centre, label: "Nouveau centre", icon: "plus", params: {action: "new"}}

      - label: "Faritany"
        children: 
          - {entity: Faritany, label: "Liste Faritany", icon: "th-list"}
          - {entity: Faritany, label: "Nouveau Faritany", icon: "plus", params: {action: "new"}}

      - label: "Ville"
        children: 
          - {entity: Ville, label: "Liste Villes", icon: "th-list"}
          - {entity: Ville, label: "Nouvelle Ville", icon: "plus", params: {action: "new"}}

      - label: "Actualite"
        children: 
          - {entity: Actualite, label: "Liste Actualites", icon: "th-list"}
          - {entity: Actualite, label: "Nouvelle Actualite", icon: "plus", params: {action: "new"}}

      - label: "DG"
        children: 
          - {entity: DG, label: "Liste Directeurs", icon: "th-list"}
          - {entity: DG, label: "Nouveau DG", icon: "plus", params: {action: "new"}}

      - label: "Mot DG"
        children: 
          - {entity: DgWord, label: "Liste mot DG", icon: "th-list"}
          - {entity: DgWord, label: "Nouveau mot DG", icon: "plus", params: {action: "new"}}

      - label: "Organigramme"
        children: 
          - {entity: Organigramme, label: "Liste Organigrammes", icon: "th-list"}
          - {entity: Organigramme, label: "Nouveau Organigramme", icon: "plus", params: {action: "new"}}
      
      - label: "Spot"
        children: 
          - {entity: Spot, label: "Liste Spots", icon: "th-list"}
          - {entity: Spot, label: "Nouveau Spot", icon: "plus", params: {action: "new"}}

      - {label: "Paramètres"}
      - label: "Utilisateur"
        children: 
          - {entity: User, label: "Liste Utilisateur", icon: "th-list"}
          - {entity: User, label: "Nouveau Utilisateur", icon: "plus", params: {action: "new"}}



  entities:
    Actualite:
      class: App\Entity\Actualite
      # templates:
      #   show: 'easyadmin/actualite/show.html.twig'
      #   edit: 'easyadmin/actualite/edit.html.twig'
      label: "Actualite"
      form:
        fields:
          - title
          - {property: 'content', type: 'text_editor'} 
          - url_video
          - datePub
          - { property: 'imageFile', type: 'vich_image' }
          - { property: 'attachements', type: 'collection', type_options: {entry_type: 'App\Form\AttachementType', by_reference: false}}
          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste Actualites "
        fields: ['title', 'content', 'datePub', {property: 'filename', type: 'image', base_path: '%uploads_actualite_path%'} ]

      show:
        fields:
          - title
          - {property: 'content', type: 'raw'}
          - datePub
          - {property: 'filename', type: 'image', base_path: '%uploads_actualite_path%'}
          - {property: 'attachements', template: 'attachement.html.twig'}

      edit:
        help: "hello there"
        fields:
          - '-tags'

      # List the entity class name you want to manage
    Centre:
      class: App\Entity\Centre
      label: "Centre"
      form:
        fields:
          - { property: 'imageFile', type: 'vich_image' }

    Faritany:
      class: App\Entity\Faritany
      label: "Faritany"

    Ville:
      class: App\Entity\Ville
      label: "Ville"

    DG:
      class: App\Entity\DG
      label: "DG"

    DgWord:
      class: App\Entity\DgWord
      label: "Mot du DG"

    Organigramme:
      class: App\Entity\Organigramme
      label: "Organigramme"

    Spot:
      class: App\Entity\Spot
      label: "Spot"

    User:
      class: App\Entity\User
      label: "Utilisateur"

    

