# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
      thumbnail:
        quality: 100
        filters: 
          thumbnail  : 
            size : [100, 150]
            mode : outbound 

      saloon_page:
        jpeg_quality: 90
        filters:
          thumbnail: {size: [300,300], mode: inset, allow_upscale: true}