easy_admin:
  entities:

    DG:
      class: App\Entity\DG
      label: "Dirécteurs généraux"
      form:
        fields:
          - grade
          - name
          - periode
          - { property: 'imageFile', type: 'vich_image' }
          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste des centres "
        fields: [ 'grade', 'name', 'periode', , {property: 'filename', type: 'image', base_path: '%dg_image_path%'} ]

      show:
        fields:
          - grade
          - name
          - periode
          - dgWords
          # - {property: 'dgWords', type: 'text'}
          - {property: 'filename', type: 'image', base_path: '%dg_image_path%'}

      # edit:
      #   help: "hello there"
      #   fields:
      #     - '-tags'
