easy_admin:
  entities:

    Organigramme:
      class: App\Entity\Organigramme
      label: "Organigramme"
      form:
        fields:
          - periode
          - { property: 'imageFile', type: 'vich_image' }

          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste des centres "
        fields: [ periode, {property: 'filename', type: 'image', base_path: '%org_image_path%'} ]
